name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version if needed

      - name: Build and Deploy
        run: |
          # If you have a build step, add it here
          # For example, if you use a static site generator, run the build command
          # npm install
          # npm run build

          # Deploy to GitHub Pages
          echo "Deploying to GitHub Pages"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages 